name: build
on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build and Package
    runs-on: windows-2019

    strategy:
      matrix:
        rust: [nightly-x86_64-msvc]
        target: [x86_64-pc-windows-msvc]
        archive-name: [NodeInject-windows.zip]

    steps:
    - name: Checkout Repositories
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
        target: ${{ matrix.target }}
        
    - name: Build Binaries and Archive
      shell: bash
      run: |
        # Build License-learning
        cd ./License-learning
        cargo build --verbose --release --target ${{ matrix.target }}
        # Build Node
        cd ../Node
        cargo build --verbose --release --target ${{ matrix.target }}
        # Prepare Archive (ZIP)
        mkdir -p archive
        cp "./Node/target/${{ matrix.target }}/release/node_inject.exe" ./archive/
        cp "./License-learning/target/${{ matrix.target }}/release/license-learning.exe" ./archive/
        cd archive
        zip -r "${{ matrix.archive-name }}" ./*
      env:
        RUST_BACKTRACE: 1
        
    - name: Upload Archive
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.archive-name }}
        path: archive/${{ matrix.archive-name }}
